name: Deploy to dev server
run-name: ${{ gitea.actor }} is deploying to dev server from ${{ gitea.ref }} 🚀

on:
  push:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest
    container: gitea.skni.umcs.pl/picto/ansible:latest
    steps:
      - name: Get latest ansible scripts from repo
        run: |
          git clone "https://gitea-deploy:${{ secrets.GIT_PASS }}@gitea.skni.umcs.pl/picto/picto-install.git"
      - name: List files
        run: |
          ls -la
        working-directory: ./picto-install
      - name: Add ssh key from secrets
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # ssh-add ~/.ssh/id_rsa
      - name: Deploy to dev server
        working-directory: ./picto-install
        run: |
          ansible-playbook -i hosts.ini -e 'gitea_password=${{ secrets.GIT_PASS }}' -e 'ansible_ssh_common_args="-o StrictHostKeyChecking=no"' -l test --key-file '~/.ssh/id_rsa' update.yml
